spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
    data: classpath:schema.sql
    initialization-mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 1000
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org.springframework.web: debug

---
spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/techmoa?useUnicode=true&characterEncoding=utf8
      username: root
      password: 1234
      connection-test-query: SELECT 1
      data-source-properties:
        zeroDateTimeBehavior: convertToNull
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 1000
  redis:
    host: ${REDIS_HOST:localhost}
  jackson:
    serialization:
      fail-on-empty-beans: false

